server {
	listen 80;
	listen [::]:80;
	server_name rei-uqode.ca;

	root /usr/share/nginx/html;

	location / {
		# root /usr/share/nginx/html;
		index index.html;
	}
	
	location ~ \.php {
		# root html;
		try_files $uri =404;
		fastcgi_pass php:9000;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		include fastcgi_params;
	}
}